name: "Initialize Dependencies"
description: "Initializes Composer and Node dependencies"
runs:
  using: "composite"
  steps:
    - name: Login to Laravel Nova
      run: composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
      env:
        NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
        NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

    - uses: actions/cache@v2
      id: vendor-cache
      with:
        path: "./vendor"
        key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

    - name: Install Composer Dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Get Yarn Cache Directory
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: "./node_modules"
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install Yarn
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: yarn install
