name: Laravel

on:
    push:
    pull_request:

jobs:
    test:

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4]
                service: ['mysql:8', 'mysql:5.7']

                include:
                    - service: 'mysql:8'
                      db: MySQL8
                    - service: 'mysql:5.7'
                      db: MySQL5

        services:
            mysql:
                image: ${{ matrix.service }}
                env:
                    MYSQL_DATABASE: testing_db
                    MYSQL_USER: testing
                    MYSQL_PASSWORD: testing
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_ROOT_HOST: "%"
                ports:
                    - 13306:3306

        name: 'PHP ${{ matrix.php }} / ${{ matrix.db }}'

        steps:
            - uses: actions/checkout@v2

            - name: Select PHP version
              uses: shivammathur/setup-php@master
              with:
                  php-version: '${{ matrix.php }}'

            - name: Start required services
              run: sudo systemctl start mysql

            - name: Create MySQL User
              run: mysql -uroot -proot -e "create user 'testing'@'%' identified by 'testing';" --port 13306

            - name: Create MySQL Database
              run: mysql -uroot -proot -e "create database testing_db;" --port 13306

            - name: Grant MySQL permissions
              run: mysql -uroot -proot -e "grant all privileges on *.* to 'testing'@'%' with grant option;" --port 13306

            - name: Copy .env
              run: php -r "file_exists('.env.testing') || copy('.env.testing', '.env');"

            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            - name: Run tests
              run: ./vendor/bin/phpunit
              env:
                DB_HOST: localhost
                DB_DATABASE: testing_db
                DB_USERNAME: testing
                DB_PASSWORD: testing

