name: Quick Checks

on:
  push:
    branches-ignore:
      - "develop"
      - "master"

jobs:
  code-analysis:
    name: "Code Analysis"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up PHP and Tools
        uses: shivammathur/setup-php@master
        with:
          php-version: "7.4"
          tools: composer:v2
          coverage: none

      - name: Initialize Dependencies
        uses: ./.github/actions/initialize-dependencies

      - name: Static Code Analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

  code-style:
    name: "Code Style"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up PHP and Tools
        uses: shivammathur/setup-php@master
        with:
          php-version: "7.4"
          tools: composer:v2, phpcs, php-cs-fixer, phpmd, phpcpd
          coverage: none

      - name: Initialize Dependencies
        uses: ./.github/actions/initialize-dependencies

      - name: Syntax Errors
        run: find app database tests config routes -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

      - name: PHP_CodeSniffer
        run: phpcs

      - name: PHP-CS-Fixer
        run: php-cs-fixer fix app database config routes tests --dry-run --diff --allow-risky=yes --config=.php_cs

      - name: PHPMD
        run: phpmd app text phpmd.xml

      - name: PHPCPD
        run: phpcpd app database config routes

      - name: Lint Assets
        run: yarn lint

  security-check:
    name: "Security Check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up PHP and Tools
        uses: shivammathur/setup-php@master
        with:
          php-version: "7.4"
          tools: composer:v2
          coverage: none

      - name: Check Composer Packages
        uses: symfonycorp/security-checker-action@v2
